language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
 - pip install -r dev-requirements.txt
addons:
  postgresql: "9.3"
script:
 - nosetests --with-coverage
after_success:
 - coverage combine
 - coveralls
sudo: false
