version: '3.1'
services:
  pytest_biblib_microservice:
    build: .
    image: biblib:latest
    container_name: pytest_biblib_microservice
    volumes:
    - ./:/app
    networks:
      - pytest_biblib_microservice
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    user: ads
    entrypoint: scripts/pytest/pytest_persistent.sh
  pytest_biblib_db:
    container_name: pytest_biblib_db
    image: postgres:12.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=biblib_microservice_test
    volumes:
      - ./scripts/pytest/support/init-db.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      - pytest_biblib_microservice
networks:
  pytest_biblib_microservice:
    driver: bridge
