"""dates included in models

Revision ID: 1c79c6e22cd5
Revises: 4fc01902d29f
Create Date: 2015-06-08 10:02:01.216103

"""

# revision identifiers, used by Alembic.
revision = '1c79c6e22cd5'
down_revision = '4fc01902d29f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('bibcode', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('absolute_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('absolute_uid')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('library_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    op.drop_table('user')
    op.drop_table('library')
    ### end Alembic commands ###
