"""empty message

Revision ID: 1c82f25a268e
Revises: 1c79c6e22cd5
Create Date: 2016-03-28 15:44:54.813824

"""

# revision identifiers, used by Alembic.
revision = '1c82f25a268e'
down_revision = '1c79c6e22cd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    ### end Alembic commands ###
