"""date created and last modified added to library table

Revision ID: 1c79c6e22cd5
Revises: 4fc01902d29f
Create Date: 2015-06-08 12:48:41.572083

"""

# revision identifiers, used by Alembic.
revision = '1c79c6e22cd5'
down_revision = '4fc01902d29f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('library', sa.Column('date_last_modified', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'date_created')
    op.drop_column('library', 'date_last_modified')
    ### end Alembic commands ###
