"""Adding the notes table and changing libraries table

Revision ID: 8feb0a6fbd27
Revises: 4039aa74290f
Create Date: 2023-08-13 21:38:18.660449

"""

# revision identifiers, used by Alembic.
revision = '8feb0a6fbd27'
down_revision = '4039aa74290f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('bibcode', sa.String(length=50), nullable=False),
    sa.Column('library_id', biblib.models.GUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
